language: cpp
compiler:
  - g++
script: make
before_script:
 - wget http://nodejs.org/dist/v0.10.13/node-v0.10.13-linux-x86.tar.gz
 - tar xzvf node-v0.10.13-linux-x86.tar.gz
 - export NODE_PATH="`pwd`/node-v0.10.13-linux-x86"
 - export PATH="`pwd`/node-v0.10.13-linux-x86/bin:$PATH"
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnss3 libnss3-dev libnss3-tools libasound2 libasound2-dev libpulse-dev libpulse0
notifications:
  recipients:
    - boemianrapsodi@gmail.com
  email:
    on_success: change
    on_failure: always
