language: cpp
compiler:
  - g++
script: make
before_script:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnss
branches:
  only:
    - master
notifications:
  recipients:
    - boemianrapsodi@gmail.com
  email:
    on_success: change
    on_failure: always
