language: cpp
compiler:
  - g++
script: make
before_script:
 - sudo apt-get update -qq
 - sudo apt-get install -qq node:i386 libnss3 libnss3-dev libnss3-tools libasound2 libasound2-dev libpulse-dev libpulse0
 - which node
 - file `which node`
notifications:
  recipients:
    - boemianrapsodi@gmail.com
  email:
    on_success: change
    on_failure: always
